[versions]
agp = "8.1.4"
activity = "1.7.2"
appcompat = "1.6.1"
benchmark = "1.2.1"
composeBom = "2023.10.01"
composeCompiler = "1.5.4"
constraintLayout = "2.1.4"
core = "1.12.0"
coroutines = "1.6.4"
concurrentFutures = "1.1.0"
curtains = "1.2.4"
dataStore = "1.0.0"
espressoCore = "3.5.1"
jUnit = "1.1.5"
kotlin = "1.9.20"
lifecycle = "2.6.2"
material = "1.9.0"
profileInstaller = "1.3.1"
rules = "1.5.0"
runtimeTracing = "1.0.0-alpha05"
tracing = "1.3.0-alpha02"
tracingPerfetto = "1.0.0"
uiAutomator = "2.3.0-alpha05"

[libraries]
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "jUnit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
benchmark-junit = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtimeTracing" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
concurrentfutures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrentFutures" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines" }
lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileInstaller" }
squareup-curtains = { group = "com.squareup.curtains", name = "curtains", version.ref = "curtains" }
tracing = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "tracing" }
tracing-perfetto = { module = "androidx.tracing:tracing-perfetto", version.ref = "tracingPerfetto" }
tracing-perfetto-binary = { module = "androidx.tracing:tracing-perfetto-binary", version.ref = "tracingPerfetto" }
ui-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

[plugins]

application = { id = "com.android.application", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "benchmark" }
library = { id = "com.android.library", version.ref = "agp" }
test = { id = "com.android.test", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
